#==============================================================================
# purpose: write tests for the mixpanel API
# author: tirthankar chakravarty
# created: 11th May 2016
# revised:
# comments:
# - before running this code, rebuild and reload the package
# - the structure of this file is the same as the file that creates the API wrapper
# - add the tests back in here before releasing the package
# -
#==============================================================================

# 1.1 get_mixpanel_annotations_annotations --------------------------------
test_mixpanel_annotations_annotations = get_mixpanel_annotations_annotations(
  api_secret = api_secret,
  from_date = Sys.Date() - ddays(100),
  to_date = Sys.Date()
)
assert_that(test_mixpanel_annotations_annotations$status_code == 200)

# 1.2 post_mixpanel_annotations_create -----------------------------
test_mixpanel_annotations_create = post_mixpanel_annotations_create(
  api_secret = api_secret,
  date = Sys.time() - ddays(20),
  description = "This is a test message generated by Tirthankar. DELETE."
)

assert_that(test_mixpanel_annotations_create$status_code == 200)
content(test_mixpanel_annotations_create, as = "text")

# test that the annotations has been posted successfully
annotations = get_mixpanel_annotations_annotations(
  api_secret = api_secret,
  from_date = Sys.Date() - ddays(25),
  to_date = Sys.Date()
)
assert_that(annotations$status_code == 200)
content(annotations)

# 1.3 post_mixpanel_annotations_update -----------------------------
test_post_mixpanel_annotations_update = post_mixpanel_annotations_update(
  api_secret = api_secret,
  date = Sys.time() - ddays(20),
  # this is hardcoded
  id = "80539",
  description = "This is a test annotation that was generated and updated by Tirthankar. DEFINITELY DELETE."
)

assert_that(test_post_mixpanel_annotations_update$status_code == 200)
content(test_post_mixpanel_annotations_update, as = "text")

# 1.4 post_mixpanel_annotations_delete -----------------------------
test_post_mixpanel_annotations_delete = post_mixpanel_annotations_delete(
  api_secret = api_secret,
  id = 80539
)

# check the status code and the contents
assert_that(test_post_mixpanel_annotations_delete$status_code == 200)
content(test_post_mixpanel_annotations_delete, as = "text")
