#==============================================================================
# purpose: write tests for the mixpanel API
# author: tirthankar chakravarty
# created: 11th May 2016
# revised:
# comments:
# - before running this code, rebuild and reload the package
# - the structure of this file is the same as the file that creates the API wrapper
# - add the tests back in here before releasing the package
# -
#==============================================================================

# get the API secret -- this is a little awkwardly put together
# looks for a system.file .API_SECRET.R
api_secret = Sys.getenv("MP_API_SECRET")

# 1.1 get_mixpanel_annotations_annotations --------------------------------
test_mixpanel_annotations_annotations = get_mixpanel_annotations_annotations(
  api_secret = api_secret,
  from_date = Sys.Date() - ddays(100),
  to_date = Sys.Date()
)
assert_that(test_mixpanel_annotations_annotations$status_code == 200)

# 1.2 post_mixpanel_annotations_create -----------------------------
test_mixpanel_annotations_create = post_mixpanel_annotations_create(
  api_secret = api_secret,
  date = Sys.time() - ddays(20),
  description = "This is a test message generated by Tirthankar. DELETE."
)

assert_that(test_mixpanel_annotations_create$status_code == 200)
content(test_mixpanel_annotations_create, as = "text")

# test that the annotations has been posted successfully
annotations = get_mixpanel_annotations_annotations(
  api_secret = api_secret,
  from_date = Sys.Date() - ddays(25),
  to_date = Sys.Date()
)
assert_that(annotations$status_code == 200)
content(annotations)

# 1.3 post_mixpanel_annotations_update -----------------------------
test_post_mixpanel_annotations_update = post_mixpanel_annotations_update(
  api_secret = api_secret,
  date = Sys.time() - ddays(20),
  # this is hardcoded
  id = "80539",
  description = "This is a test annotation that was generated and updated by Tirthankar. DEFINITELY DELETE."
)

assert_that(test_post_mixpanel_annotations_update$status_code == 200)
content(test_post_mixpanel_annotations_update, as = "text")

# 1.4 post_mixpanel_annotations_delete -----------------------------
test_post_mixpanel_annotations_delete = post_mixpanel_annotations_delete(
  api_secret = api_secret,
  id = 80539
)

# check the status code and the contents
assert_that(test_post_mixpanel_annotations_delete$status_code == 200)
content(test_post_mixpanel_annotations_delete, as = "text")


# 2 endpoint: events ------------------------------------------------------

# 2.1 get_mixpanel_events_events ------------------------------------------
test_get_mixpanel_events_events = get_mixpanel_events_events(
  api_secret = api_secret,
  event = paste0('["', "Page Viewed", '"]'),
  type = "unique",
  unit = "day",
  interval = 100
)

# check the return object
assert_that(test_get_mixpanel_events_events$status_code == 200)
content(test_get_mixpanel_events_events, as = "text")

# 2.2 get_mixpanel_events_top ---------------------------------------------
test_get_mixpanel_events_top = get_mixpanel_events_top(
  api_secret = api_secret,
  type = "unique",
  limit = 100
)

# check the return object
assert_that(test_get_mixpanel_events_top$status_code == 200)
content(test_get_mixpanel_events_top, as = "text")

# 2.3 get_mixpanel_events_names -------------------------------------------
test_get_mixpanel_events_names = get_mixpanel_events_names(
  type = "unique",
  limit = 100
)

# check the return object
assert_that(test_get_mixpanel_events_names$status_code == 200)
content(test_get_mixpanel_events_names, as = "text")

# 3. endpoint: event properties -------------------------------------------

# 3.1 get_mixpanel_event_properties_properties ----------------------------
test_get_mixpanel_event_properties_properties = get_mixpanel_event_properties_properties(
  api_secret = api_secret,
  event = "App Launched",
  name = "Platform",
  values = NULL,
  type = "general",
  unit = "day",
  interval = 100,
  format = "json",
  limit = 100
)

# check the response
assert_that(
  test_get_mixpanel_event_properties_properties$status_code == 200
)
content(test_get_mixpanel_event_properties_properties, as = "text")

# 3.2 get_mixpanel_event_properties_top -----------------------------------
test_get_mixpanel_event_properties_top = get_mixpanel_event_properties_top(
  api_secret = api_secret,
  event = "Page Viewed",
  limit = 100
)

# check the response
assert_that(test_get_mixpanel_event_properties_top$status_code == 200)
content(test_get_mixpanel_event_properties_top, as = "text")

# # 3.3 get_mixpanel_event_properties_values --------------------------------
test_get_mixpanel_event_properties_values = get_mixpanel_event_properties_values(
  api_secret = api_secret,
  event = "Page Viewed",
  name = "Page Type",
  limit = 100,
  bucket = NULL
)

# check the response
assert_that(test_get_mixpanel_event_properties_values$status_code == 200)
content(test_get_mixpanel_event_properties_values, as = "text")

# 4. endpoint: funnels ----------------------------------------------------

# 4.1 get_mixpanel_funnels_funnels ----------------------------------------
test_get_mixpanel_funnels_funnels = get_mixpanel_funnels_funnels(
  api_secret = api_secret,
  funnel_id = 1692025,
  from_date = Sys.Date() - ddays(20),
  to_date = Sys.Date(),
  length = NULL,
  interval = NULL,
  unit = "day",
  on = NULL,
  where = NULL,
  limit = NULL
)

# check the response
assert_that(test_get_mixpanel_funnels_funnels$status_code == 200)
content(test_get_mixpanel_funnels_funnels, as = "text")

# 4.2 get_mixpanel_funnels_list -------------------------------------------
test_get_mixpanel_funnels_list = get_mixpanel_funnels_list(
  api_secret = api_secret
)

# check the response
assert_that(test_get_mixpanel_funnels_list$status_code == 200)
content(test_get_mixpanel_funnels_list, as = "text")

